# Generated by Django 2.0.2 on 2018-03-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('expense_category', models.CharField(choices=[('GR', 'Grocery'), ('EN', 'Entertainment'), ('VE', 'Vehicle'), ('MI', 'miscellaneous')], default='GR', max_length=2)),
                ('cash', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
